spring.application.name=order-system-lab
spring.datasource.url=jdbc:mysql://localhost:3306/order_system_lab?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Taipei
spring.datasource.username=root
spring.datasource.password=root123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080